Attribute VB_Name = "mAddChart"
Option Explicit

'---------------------------------------------------------------------------------------
' Procedure : AddNewChart
' Author    : Kane
' Date      : 02/05/2016
' Purpose   : Adds a new (empty, undefined) chart to a sheet and will increment the index number in the chart name
' Returns:
'   Chart = handle to the new chart
' Example:
'           Dim MyChart As Chart
'           Set MyChart = AddNewChart("MyDataChart")
'---------------------------------------------------------------------------------------
Public Function AddNewChart(Optional ByVal ChartBaseName As String = vbNullString, Optional ByVal IncrementIndex As Boolean = True, Optional ByVal sht As Worksheet) As Chart
    Dim shpTmp As Shape
    Dim cht As Chart
    Dim ChtObj As ChartObject
    Dim ChtNumMax As Long
    Dim ChtNum As Long
    Dim ChartNewName As String
    Dim i As Long

    On Error GoTo AddNewChart_Error

    ChtNumMax = 0
    If sht Is Nothing Then Set sht = ActiveSheet
    If sht Is Nothing Then Exit Function
    
    If ChartBaseName = vbNullString Then
        ChartBaseName = "AutoGeneratedChart"
        IncrementIndex = True
    End If
    If IncrementIndex Then
        'look for next chart number
        For Each ChtObj In sht.ChartObjects
            If Left(ChtObj.Name, Len(ChartBaseName)) = ChartBaseName Then
                ChtNum = 1
                If Len(ChtObj.Name) > Len(ChartBaseName) Then
                    ChtNum = Val(Right(ChtObj.Name, Len(ChtObj.Name) - Len(ChartBaseName)))
                End If
                If ChtNum > ChtNumMax Then ChtNumMax = ChtNum
            End If
        Next
        ChartNewName = ChartBaseName & ChtNumMax + 1
    Else
        ChartNewName = ChartBaseName
    End If
    
    On Error Resume Next
    Set shpTmp = sht.Shapes.AddChart
    If Err <> 0 Then Exit Function
    On Error GoTo 0
    shpTmp.Name = ChartNewName
    shpTmp.AlternativeText = ChartNewName & vbCrLf
    shpTmp.Title = ChartBaseName
    Set cht = shpTmp.Chart
    'remove all series in the chart
    If cht.SeriesCollection.Count > 0 Then
        For i = cht.SeriesCollection.Count To 1 Step -1
            cht.SeriesCollection(i).Delete
        Next
    End If
    Set AddNewChart = cht
    
    Set cht = Nothing
    Set ChtObj = Nothing
    Set shpTmp = Nothing

    On Error GoTo 0
    Exit Function
AddNewChart_Error:
    MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure AddNewChart of Module Module1"
End Function

